name: CI - Build, Test & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build, Test, and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=cobertura

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          input-file: coverage/coverage.cobertura.xml
          output-file: coverage-badge.svg
          badge-style: flat

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add coverage-badge.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push

      - name: Upload test results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
