name: CI - Build, Test & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write 

jobs:
  build-test:
    name: Build, Test, and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator \
            -reports:"coverage/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"Html;Badges" \
            -assemblyfilters:"+*" \
            -classfilters:"+*"

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add coverage-report/badge_linecoverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push

      - name: Upload test results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage-report/
