@StoryBooks_HostAddress = http://localhost:5097

GET {{StoryBooks_HostAddress}}/weatherforecast/
Accept: application/json

###

@search_word=string
GET {{StoryBooks_HostAddress}}/api/storybook/search?search_word={{search_word}}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1QGdtYWlsLmNvbSIsInVpZCI6ImJmMDZkOGI0LTA1YmEtNGZjMC04MjRlLTcxMzdiNjg1ZDllZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJtZW1lIiwiZXhwIjoxNzU5NDE1NjkwLCJpc3MiOiJTdG9yeUJvb2tzIiwiYXVkIjoiU3RvcnlCb29rc1VzZXJzIn0.QYbfqtersGx2xJOpWM-GqxbM-ISYRjm2k835j_X90Uk
GET {{StoryBooks_HostAddress}}/api/storybook/ping
Authorization: Bearer {{token}}

###

POST {{StoryBooks_HostAddress}}/auth/login
Authorization:Bearer {{token}}
Content-Type: application/json

{
  "email": "umaima@gmail.com",
  "password": "123Umaima!"
}

###

POST {{StoryBooks_HostAddress}}/api/auth/register
Authorization: bearer {{$bearerToken}}
Content-Type: application/json

{
  //RegisterDto
}

###

POST {{StoryBooks_HostAddress}}/api/auth/login
Authorization: bearer {{$bearerToken}}
Content-Type: application/json

{
  "email": "umaima@gmail.com",
  "password": "123Umaima!"
}

###

GET {{StoryBooks_HostAddress}}/api/storybook/ping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1bWFpbWFAZ21haWwuY29tIiwidWlkIjoiYjc3OWE2YzMtMjg1MC00MmYxLWEzYzUtNDhmMjcyMTg3YTY3IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlVtYWltIEFzYWQiLCJleHAiOjE3NTk0ODUxNTMsImlzcyI6IlN0b3J5Qm9va3MiLCJhdWQiOiJTdG9yeUJvb2tzVXNlcnMifQ.oEsIVSzo9F5nyOhZyLsrB_oPTEDLXGUvrol2u319s50
###

POST {{StoryBooks_HostAddress}}/api/storybook
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1bWFpbWFAZ21haWwuY29tIiwidWlkIjoiYjc3OWE2YzMtMjg1MC00MmYxLWEzYzUtNDhmMjcyMTg3YTY3IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlVtYWltIEFzYWQiLCJleHAiOjE3NTk0ODIxMzAsImlzcyI6IlN0b3J5Qm9va3MiLCJhdWQiOiJTdG9yeUJvb2tzVXNlcnMifQ.Xc3wweCuaO4Ql0YWGcxsfh1GeaoeWGZI3OPGhefLw-E
Content-Type: application/json

{
  //CreateStoryBookDTO
}

###

@id=0
GET {{StoryBooks_HostAddress}}/api/storybook/{{id}}
Authorization: bearer {{$bearerToken}}

###

GET {{StoryBooks_HostAddress}}/api/storybook/{{id}}
Authorization: bearer {{$bearerToken}}

###
